esphome:
  name: raingage
  friendly_name: "Raingage"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    then:
      - logger.log:
          level: INFO
          format: "Wi-Fi connected successfully."
  ap:
    ap_timeout: "0s"

  manual_ip:
    static_ip: 192.168.254.254
    gateway: 192.168.254.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1
    dns2: 192.168.254.1

captive_portal:

globals:
  - id: tip_count
    type: int
    restore_value: true
    initial_value: '0'

web_server:
  port: 80
  include_internal: True
  version: 3

#===========================================================================

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: false
    name: "Rain Gauge Tip"
    id: rain_tip
    device_class: opening  
    filters:
      - delayed_on: 50ms
    on_press:
      then:
        - lambda: |-
            id(tip_count) += 1;
            ESP_LOGD("rain", "Tip detected! Total tips now: %d", id(tip_count));

sensor:
  - platform: template
    name: "Rain Tips Total"
    id: tip_counter
    lambda: return id(tip_count);
    update_interval: 1min
    unit_of_measurement: "tips"
    icon: "mdi:counter"
    accuracy_decimals: 0

  - platform: template
    name: "Rainfall Total"
    id: rainfall_total
    lambda: |-
      return id(tip_count) * 0.01;
    update_interval: 1min
    unit_of_measurement: "in"
    icon: "mdi:weather-rainy"
    accuracy_decimals: 2
    state_class: total_increasing

number:
  - platform: template
    name: "Set Rainfall Total"
    id: set_rainfall_total
    min_value: 0
    max_value: 50
    step: 0.01          # Changed to 0.01 for finer control
    unit_of_measurement: "in"
    icon: "mdi:weather-rainy"
    set_action:
      then:
        - lambda: |-
            float new_inches = x;
            int new_tips = static_cast<int>(round(new_inches * 100.0));  // or / 0.01
            id(tip_count) = new_tips;
            ESP_LOGI("rain", "Rainfall reset to %.2f in (%d tips)", new_inches, new_tips);
            id(rainfall_total).publish_state(new_inches);
            id(tip_counter).publish_state(static_cast<float>(new_tips));